-- Tạo các bảng
-- Tạo bảng KHACH_HANG

CREATE TABLE KHACH_HANG (
    MAKH VARCHAR(10) PRIMARY KEY,
    HOTEN NVARCHAR(100) NOT NULL,
    SDT VARCHAR(15) NOT NULL,
    GIOITINH NVARCHAR(10) CHECK (GIOITINH IN (N'Nam', N'Nữ', N'Khác')),
    EMAIL VARCHAR(100) UNIQUE,
    NGAYSINH DATE
);
-- Thêm ràng buộc và kiểm tra
ALTER TABLE KHACH_HANG 
ADD CONSTRAINT CHK_SDT CHECK (SDT LIKE '[0-9]%' AND LEN(SDT) >= 10);

ALTER TABLE KHACH_HANG 
ADD CONSTRAINT CHK_EMAIL CHECK (EMAIL LIKE '%@%.%');

ALTER TABLE KHACH_HANG 
ADD CONSTRAINT CHK_NGAYSINH CHECK (NGAYSINH <= GETDATE());
-- 2. Tao bang Thanh Pho 
CREATE TABLE THANH_PHO (
    MATP VARCHAR(10) PRIMARY KEY,
    TENTP NVARCHAR(100) NOT NULL
);

-- 3. Tạo bảng QUAN_HUYEN  
CREATE TABLE QUAN_HUYEN (
    MAQ VARCHAR(10) PRIMARY KEY,
    TENQUAN NVARCHAR(100) NOT NULL,
    MATP VARCHAR(10) NOT NULL,
    
    -- Tạo khóa ngoại
    CONSTRAINT FK_QUAN_THANH_PHO 
        FOREIGN KEY (MATP) REFERENCES THANH_PHO(MATP)
);

-- 4. Tạo bảng PHUONG_XA
CREATE TABLE PHUONG_XA (
    MAP VARCHAR(10) PRIMARY KEY,
    TENPHUONG NVARCHAR(100) NOT NULL,
    MAQUAN VARCHAR(10) NOT NULL,
    
    -- Tạo khóa ngoại
    CONSTRAINT FK_PHUONG_QUAN 
        FOREIGN KEY (MAQUAN) REFERENCES QUAN_HUYEN(MAQ)
);

-- 5. Tạo bảng DUONG_PHO
CREATE TABLE DUONG_PHO (
    MADUONG VARCHAR(10) PRIMARY KEY,
    TENDUONG NVARCHAR(150) NOT NULL,
    MAPHUONG VARCHAR(10) NOT NULL,
    
    -- Tạo khóa ngoại
    CONSTRAINT FK_DUONG_PHUONG 
        FOREIGN KEY (MAPHUONG) REFERENCES PHUONG_XA(MAP)
);
-- Tạo bảng DIA_CHI_KHACH_HANG
CREATE TABLE DIA_CHI_KHACH_HANG (
    MADIACHI VARCHAR(10) PRIMARY KEY,
    MAKH VARCHAR(10) NOT NULL,
    SONHA NVARCHAR(20) NOT NULL,
    MADUONG VARCHAR(10) NOT NULL,
    
    -- Tạo khóa ngoại tham chiếu đến bảng KHACH_HANG
    CONSTRAINT FK_DIACHI_KHACHHANG 
        FOREIGN KEY (MAKH) REFERENCES KHACH_HANG(MAKH),
    
    -- Tạo khóa ngoại tham chiếu đến bảng DUONG_PHO
    CONSTRAINT FK_DIACHI_DUONGPHO 
        FOREIGN KEY (MADUONG) REFERENCES DUONG_PHO(MADUONG)
);
-- Tao bang Nhan Vien 
CREATE TABLE NHAN_VIEN (
    MANV VARCHAR(10) PRIMARY KEY,
    HOTENNV NVARCHAR(100) NOT NULL,
    SDT VARCHAR(15) NOT NULL,
    GIOITINH NVARCHAR(10) CHECK (GIOITINH IN (N'Nam', N'Nữ', N'Khác')),
    EMAIL VARCHAR(100) UNIQUE,
    NGAYSINH DATE
);

-- Thêm ràng buộc và kiểm tra cho bảng NHAN_VIEN
ALTER TABLE NHAN_VIEN 
ADD CONSTRAINT CHK_NV_SDT CHECK (SDT LIKE '[0-9]%' AND LEN(SDT) >= 10);

ALTER TABLE NHAN_VIEN 
ADD CONSTRAINT CHK_NV_EMAIL CHECK (EMAIL LIKE '%@%.%');

ALTER TABLE NHAN_VIEN 
ADD CONSTRAINT CHK_NV_NGAYSINH CHECK (NGAYSINH <= GETDATE());

-- Tao bang dia chi nhan vien
CREATE TABLE DIA_CHI_NHAN_VIEN (
    MADIACHI VARCHAR(10) PRIMARY KEY,
    MANV VARCHAR(10) NOT NULL,
    SONHA NVARCHAR(20) NOT NULL,
    MADUONG VARCHAR(10) NOT NULL,
    
    -- Tạo khóa ngoại tham chiếu đến bảng NHAN_VIEN
    CONSTRAINT FK_DIACHI_NHANVIEN 
        FOREIGN KEY (MANV) REFERENCES NHAN_VIEN(MANV),
    
    -- Tạo khóa ngoại tham chiếu đến bảng DUONG_PHO
    CONSTRAINT FK_DIACHI_NV_DUONGPHO 
        FOREIGN KEY (MADUONG) REFERENCES DUONG_PHO(MADUONG)
);
-- Tao bang Can Ho 
CREATE TABLE CAN_HO (
    MACH VARCHAR(10) PRIMARY KEY,
    DIENTICH DECIMAL(6,2) NOT NULL CHECK (DIENTICH > 0),
    SOPHONG INT NOT NULL CHECK (SOPHONG > 0),
    TINHTRANG NVARCHAR(20) NOT NULL CHECK (TINHTRANG IN (N'Trống', N'Đã thuê', N'Đang sửa chữa', N'Tạm ngưng')),
    GIATHUE DECIMAL(12,2) NOT NULL CHECK (GIATHUE > 0),
    SONHA NVARCHAR(20) NOT NULL  -- Số căn hộ như P.101, A.205...
);
-- Thêm ràng buộc kiểm tra số nhà không rỗng
ALTER TABLE CAN_HO 
ADD CONSTRAINT CHK_CH_SONHA_NOT_EMPTY 
CHECK (LTRIM(RTRIM(SONHA)) != '');

-- Tao bang Hop Dong 
CREATE TABLE HOP_DONG (
    MAHOPDONG VARCHAR(10) PRIMARY KEY,
    MAKH VARCHAR(10) NOT NULL,
    MACH VARCHAR(10) NOT NULL,
    NGAYKY DATE NOT NULL,
    THOIHAN_HOPDONG INT NOT NULL CHECK (THOIHAN_HOPDONG > 0), -- Số tháng
    TIENTHUE DECIMAL(12,2) NOT NULL CHECK (TIENTHUE > 0),
    MANV_PHUTRACH VARCHAR(10) NOT NULL,
    
    -- Tạo khóa ngoại tham chiếu đến bảng KHACH_HANG
    CONSTRAINT FK_HOPDONG_KHACHHANG 
        FOREIGN KEY (MAKH) REFERENCES KHACH_HANG(MAKH),
    
    -- Tạo khóa ngoại tham chiếu đến bảng CAN_HO
    CONSTRAINT FK_HOPDONG_CANHO 
        FOREIGN KEY (MACH) REFERENCES CAN_HO(MACH),
    
    -- Tạo khóa ngoại tham chiếu đến bảng NHAN_VIEN
    CONSTRAINT FK_HOPDONG_NHANVIEN 
        FOREIGN KEY (MANV_PHUTRACH) REFERENCES NHAN_VIEN(MANV)
);